/**
 * Hand-maintained API-adjacent shapes that the OpenAPI spec does not describe.
 *
 * Everything in `./generated.ts` is regenerated by `pnpm gen:api` and must not
 * be edited. Anything that has to be written by hand belongs here instead, so a
 * regeneration never silently drops it.
 *
 * Keep this file small. If a shape gains a documented endpoint upstream, delete
 * it here and import the generated DTO instead.
 */

/**
 * A driver row as returned by the Supabase RPCs in `lib/supabase/supabase-rpc.ts`
 * (`get_drivers_by_ids`, `update_driver_profile`, `get_drivers_paginated`).
 *
 * Not an API DTO: hikyaku-api creates drivers via `POST /api/v1/users`
 * (see `CreateUserDto` / `DriverMetadataDto`), but reads go straight to Postgres,
 * so this shape tracks the RPC return columns rather than the spec.
 */
export interface ListDriverDto {
  id: string
  email: string
  avatar_url: string | null
  phone_number: string
  display_name: string
  driver_license: string | null
  license_expiry: string | null
  vehicle_id?: string
  vehicle_plate?: string
  vehicle_make?: string
  vehicle_model?: string
}

